version: '2'
services:
  myelasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  mykibana:
    image: kibana
    ports:
      - "5601:5601"
    links:
      - myelasticsearch:elasticsearch
  testlogstash:
    build: logstash/
    links:
      - myelasticsearch:elasticsearch
  mygrafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - myelasticsearch:elasticsearch