version: '2'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
  logstash:
    build: logstash/
    ports:
      - "12201:12201"
      - "12201:12201/udp"
    links:
      - elasticsearch:elasticsearch
